### ISSUE TITLE
Automate release building

### ISSUE THREAD

**Issue by sungo** [joyent/conch-shell#12]
For GH releases, we'll need to build binaries for linux x86, linux arm, macos, and smartos. Need to automate that process.

This should be pretty easy using GOOS *except* for smartos. There's no working illumos GOOS target so we'll probably have to build that one by hand, unless we get lucky and they add the illumos target before we get to 1.0.0.

**Comment by sungo** [comment]
The build for solaris is failing due to an issue in tcnksm/go-input

```
vendor/github.com/tcnksm/go-input/read.go:42:28: i.rawRead undefined (type *UI has no field or method rawRead)
vendor/github.com/tcnksm/go-input/read.go:49:41: undefined: LineSep
```

**Comment by sungo** [comment]
There's an issue on solaris too with the progressbar library. "Solved" that by moving the MBO report code out of the conch shell in to conch-mbo in 27d9168422c003b71ca5499ef1025281e2b07369

**Comment by sungo** [comment]
Regarding go-input, the library doesn't support solaris, code wise. Of course that's not documented.

What's happening is that go-input has a _unix variant for reading from a terminal. Its "+build" directive, however, only includes linux, darwin, and freebsd ( https://github.com/tcnksm/go-input/blob/master/read_unix.go#L1 ). Adding solaris to it causes:
```
vendor/github.com/tcnksm/go-input/read_unix.go:25:19: undefined: terminal.MakeRaw
vendor/github.com/tcnksm/go-input/read_unix.go:29:8: undefined: terminal.Restore
```
"terminal" there is "golang.org/x/crypt/ssh/terminal" which certain has those functions. So something else weird is going on.

However, go-input hasn't had a commit or recognized a PR since April 2017 and since the shell only uses it in one place (prompting for info in profile creation), I'm more inclined to go find a better library.

**Comment by sungo** [comment]
I take back what I said in the original post about SmartOS being problematic. As of 
bbcad6e, we have a solaris/amd64 build that works on SmartOS 17.3.0 64bit just fine. Tested in JPC on a base-64 instance.

**Comment by sungo** [comment]
I've been looking at changelog generation. If we just want to use github data (issues, PRs, etc), this ruby gem/cli app generates a pretty shiny changelog: https://github.com/skywinder/github-changelog-generator

If we want to just use commit logs, we can use the CLI from the angular folks since we're kinda using their commit syntax. https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-cli

I lean towards using GH based changelogs, rather than commit based. The target audience here is folks that have no interest in how the sausage is made. In fact, this app exists specifically so no one but us worries about the how. So, changelogs based on git produce files that are only valuable to developers, and not our users. If we're using GH properly, then the changelogs generated from issues should be useful to our target audience.

**Comment by sungo** [comment]
Looks like we can build everywhere we need to and have changelog generation going. I'd like to eventually get reproducible builds ( like https://github.com/restic/builder ) but not today.
